services:
  # Azurite (Azure Storage Emulator)
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - ./docker/data:/data
    # Run azurite and allow outside access
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data"
  code-push-server:
    build: .
    container_name: code-push-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - azurite