services:
  # Redis (for caching)
  redis:
    image: redis:latest
    container_name: redis
#    ports:
#      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
  # PostgreSQL (for database)
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_USER=codepush
      - POSTGRES_PASSWORD=codepush
      - POSTGRES_DB=codepush
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  # CodePush Server
  code-push-server:
    build: .
    container_name: code-push-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  redis-data:
  postgres-data: